name: 🚀 Publish Storybook to Github Pages 

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: bun install
          build_command: bun run build-storybook
          path: storybook-static
          checkout: false
